export const types = {
    //Sync
    FILL_TODOS:                  'FILL_TODOS',
    CREATE_TODO:                 'CREATE_TODO',
    CLEAR_TODOS:                 'CLEAR_TODOS',
    REMOVE_TODO:                 'REMOVE_TODO',
    UPDATE_TODO:                 'UPDATE_TODO',
    TOGGLE_COMPLETED_TODO:       'TOGGLE_COMPLETED_TODO',
    ALL_COMPLETED_TODOS:         'ALL_COMPLETED_TODOS',
    TOGGLE_PRIORITY_TODO:        'TOGGLE_PRIORITY_TODO',
    //Async
    FETCH_TODOS_ASYNC:           'FETCH_TODOS_ASYNC',
    CREATE_TODO_ASYNC:           'CREATE_TODO_ASYNC',
    REMOVE_TODO_ASYNC:           'REMOVE_TODO_ASYNC',
    TOGGLE_COMPLETED_TODO_ASYNC: 'TOGGLE_COMPLETED_TODO_ASYNC',
    ALL_COMPLETED_TODOS_ASYNC:   'ALL_COMPLETED_TODOS_ASYNC',
    TOGGLE_PRIORITY_TODO_ASYNC:  'TOGGLE_PRIORITY_TODO_ASYNC',
    UPDATE_TODO_ASYNC:           'UPDATE_TODO_ASYNC',
};
